name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: recon
      run: ls
        
#     - name: Build archive
#       run: |
#         xcodebuild -sdk iphoneos -project Azure\ sample.xcodeproj \
#           -configuration Release -scheme Azure-sample \
#           -derivedDataPath DerivedData \
#           -archivePath DerivedData/Archive/Azure-sample archive
    - name: Build App
      run: xcodebuild -project "Azure-sample/AzureSample/AzureSample.xcodeproj" -scheme "AzureSample" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
#     - name: Export Archive
#       run: |
#         xcodebuild -exportArchive \
#           -archivePath DerivedData/Archive/Azure-sample.xcarchive \
#           -exportOptionsPlist provisioning/App-Store.plist \
#           -exportPath DerivedData/ipa


